sonar.projectKey=vivek1251_devsecops-pipeline
sonar.organization=vivek1251
sonar.sources=app
sonar.language=py

sonar.exclusions=**/tests/**,**/__pycache__/**,**/*.pyc
sonar.python.version=3.11
sonar.qualitygate.wait=true